### ISSUE TITLE
sdk/network/azuresecgroup

### ISSUE THREAD

**Issue by hrodz13** [Azure-Refactor/circuit-oneops-1#10]
Upgrade azure_mgmt_network gem from 0.1.1 to 0.8.0 in the azuresecgroup cookbook

**Comment by samawia-moin-confiz** [comment]
Updated network security group library which requires upgrading azure_mgmt_network gem from 0.1.1 to 0.8.0 in azuresecgroup cookbook. Updated code has been merged in sdk/upgrade/0.8.0 branch.
