### ISSUE TITLE
sdk/dns/azuredns

### ISSUE THREAD

**Issue by hrodz13** [Azure-Refactor/circuit-oneops-1#11]
Integrate azure_mgmt_dns gem version 0.8.0 into the azuredns cookbook and remove the rest-client calls.

**Comment by samawia-moin-confiz** [comment]
Hi @hrodz13 

Currently azuredns is using rest-client calls because azure sdk didn't provide any support for dns. 
azuredns is not a part of network sdk.
Azure SDK now supports dns as a separate gem `azure_mgmt_dns`. We need to migrate azuredns cookbook to the latest gem using `azure_mgmt_dns`.

**Comment by samawia-moin-confiz** [comment]
As azuredns cookbook is using Rest-client for API calls, so we are not taking up on this for now, we will update this cookbook in Phase 2  ( Update to Fog-azurerm).

**Comment by waqar-haider-confiz** [comment]
Public IP for Azure DNS has been updated for latest SDK gem version 0.8.0. Branch _sdk/upgrade-pip/0.8.0_ merged in main branch i.e. _sdk/upgrade/0.8.0_
