### ISSUE TITLE
sdk/network/azuregateway

### ISSUE THREAD

**Issue by hrodz13** [Azure-Refactor/circuit-oneops-1#12]
Upgrade azure_mgmt_network gem from 0.1.1 to 0.8.0 in the azuregateway cookbook

**Comment by zeeshan-arshad-confiz** [comment]
Updated application gateway library which requires upgrading azure_mgmt_network gem from 0.1.1 to 0.8.0 in azuregateway cookbook. Updated code has been merged in sdk/upgrade/0.8.0 branch.
Unit tests for application gateway library are also updated.
