### ISSUE TITLE
sdk/compute/azurekeypair

### ISSUE THREAD

**Issue by zeeshan-arshad-confiz** [Azure-Refactor/circuit-oneops-1#17]
Upgrade azure_mgmt_compute gem from 0.1.1 to 0.8.0 in the azurekeypair cookbook

**Comment by samawia-moin-confiz** [comment]
Updated Availability_set_manager library which requires upgrading azure_mgmt_compute gem from 0.1.1 to 0.8.0 in azurekeypair cookbook. Updated code has been merged in `sdk/upgrade/0.8.0` branch.
