### ISSUE TITLE
fogazurerm/network/azure

### ISSUE THREAD

**Issue by waqar-haider-confiz** [Azure-Refactor/circuit-oneops-1#28]
Update azure cookbook to use Fog-ARM. This include following
[NIC, Subnet, Virtual Network, Public IP]

- Refactor your recipe into library and recipe format.
- Make sure your library code uses Fog ARM instead of Azure SDK calls
- Write RSpec unit test for library code with 100% coverage. Please attach coverage report with ticket
- Static analysis using rubocop, foodcritic and Ruby Mine
- Integration testing for recipe
- Incorporate peer code review feedback

**Comment by zeeshan-arshad-confiz** [comment]
Updated azure cookbook to use Fog-ARM. Unit tests are also done with 100% test coverage. This task include following libraries:
[NIC, Subnet, Virtual Network, Public IP]
Updated code has been merged in `feature/fog-arm-migration` branch.
