### ISSUE TITLE
Generic Interface for Library Initialization

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [Azure-Refactor/circuit-oneops-1#31]
Some azure cookbook libraries, such as the Network Interface Card Library, are initialized expecting an active token as a parameter. This should be re-factored to use the credentials information provided inside of the node instead.

**Comment by zeeshan-arshad-confiz** [comment]
Implementation is complete. Code will be merged into `feature/fog-arm-migration` after incorporating peer review changes.

**Comment by samawia-moin-confiz** [comment]
Code has been merged into `feature/fog-arm-migration`.
