### ISSUE TITLE
Use Fog models instead of SDK Enums

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [Azure-Refactor/circuit-oneops-1#32]
Use Fog model enums in place of SDK enums in OneOps

**Comment by zeeshan-arshad-confiz** [comment]
Implementation is complete. Code will be merged into `feature/fog-arm-migration` after incorporating peer review changes.

**Comment by bilal-naeem-confiz** [comment]
Branch merged into `feature/fog-arm-migration`
