### ISSUE TITLE
Unit tests for azure_base cookbook

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [Azure-Refactor/circuit-oneops-1#41]
The cookbook `azure_base` contains the following libraries
- azure_base_manager
- resource_group_manager
- availability_set_manager

Write RSpec unit tests for these libraries.

**Comment by zeeshan-arshad-confiz** [comment]
Unit tests are done for following azure_base libraries with 100% code coverage.
Updated code has been merged in `feature/fog-arm-migration` branch.
