### ISSUE TITLE
sdk/network/azure

### ISSUE THREAD

**Issue by hrodz13** [Azure-Refactor/circuit-oneops-1#8]
Upgrade azure_mgmt_network gem from 0.1.1 to 0.8.0 in the azure cookbook

**Comment by zeeshan-arshad-confiz** [comment]
Updated network interface card, subnet, virtual network and public IP library which requires upgrading azure_mgmt_network gem from 0.1.1 to 0.8.0 in azure cookbook. Updated code has been merged in sdk/upgrade/0.8.0 branch.
