### ISSUE TITLE
sdk/network/azure_lb

### ISSUE THREAD

**Issue by hrodz13** [Azure-Refactor/circuit-oneops-1#9]
Upgrade azure_mgmt_network gem from 0.1.1 to 0.8.0 in the azure_lb cookbook

**Comment by samawia-moin-confiz** [comment]
Updated azure_lb cookbook which requires upgrading azure_mgmt_network gem from 0.1.1 to 0.8.0. Code has been merged in sdk/upgrade/0.8.0 branch.
